/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as ToolsSplitPdfRouteImport } from './routes/tools.split-pdf'
import { Route as ToolsRotatePdfRouteImport } from './routes/tools.rotate-pdf'
import { Route as ToolsPdfToImageRouteImport } from './routes/tools.pdf-to-image'
import { Route as ToolsMergePdfRouteImport } from './routes/tools.merge-pdf'
import { Route as ToolsImageToPdfRouteImport } from './routes/tools.image-to-pdf'
import { Route as ToolsDeletePagesRouteImport } from './routes/tools.delete-pages'
import { Route as ToolsCompressPdfRouteImport } from './routes/tools.compress-pdf'
import { Route as ToolsSlugRouteImport } from './routes/tools.$slug'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSplitPdfRoute = ToolsSplitPdfRouteImport.update({
  id: '/tools/split-pdf',
  path: '/tools/split-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRotatePdfRoute = ToolsRotatePdfRouteImport.update({
  id: '/tools/rotate-pdf',
  path: '/tools/rotate-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPdfToImageRoute = ToolsPdfToImageRouteImport.update({
  id: '/tools/pdf-to-image',
  path: '/tools/pdf-to-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsMergePdfRoute = ToolsMergePdfRouteImport.update({
  id: '/tools/merge-pdf',
  path: '/tools/merge-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsImageToPdfRoute = ToolsImageToPdfRouteImport.update({
  id: '/tools/image-to-pdf',
  path: '/tools/image-to-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsDeletePagesRoute = ToolsDeletePagesRouteImport.update({
  id: '/tools/delete-pages',
  path: '/tools/delete-pages',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCompressPdfRoute = ToolsCompressPdfRouteImport.update({
  id: '/tools/compress-pdf',
  path: '/tools/compress-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSlugRoute = ToolsSlugRouteImport.update({
  id: '/tools/$slug',
  path: '/tools/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/tools/compress-pdf': typeof ToolsCompressPdfRoute
  '/tools/delete-pages': typeof ToolsDeletePagesRoute
  '/tools/image-to-pdf': typeof ToolsImageToPdfRoute
  '/tools/merge-pdf': typeof ToolsMergePdfRoute
  '/tools/pdf-to-image': typeof ToolsPdfToImageRoute
  '/tools/rotate-pdf': typeof ToolsRotatePdfRoute
  '/tools/split-pdf': typeof ToolsSplitPdfRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/tools/compress-pdf': typeof ToolsCompressPdfRoute
  '/tools/delete-pages': typeof ToolsDeletePagesRoute
  '/tools/image-to-pdf': typeof ToolsImageToPdfRoute
  '/tools/merge-pdf': typeof ToolsMergePdfRoute
  '/tools/pdf-to-image': typeof ToolsPdfToImageRoute
  '/tools/rotate-pdf': typeof ToolsRotatePdfRoute
  '/tools/split-pdf': typeof ToolsSplitPdfRoute
  '/tools': typeof ToolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/tools/compress-pdf': typeof ToolsCompressPdfRoute
  '/tools/delete-pages': typeof ToolsDeletePagesRoute
  '/tools/image-to-pdf': typeof ToolsImageToPdfRoute
  '/tools/merge-pdf': typeof ToolsMergePdfRoute
  '/tools/pdf-to-image': typeof ToolsPdfToImageRoute
  '/tools/rotate-pdf': typeof ToolsRotatePdfRoute
  '/tools/split-pdf': typeof ToolsSplitPdfRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/tools/$slug'
    | '/tools/compress-pdf'
    | '/tools/delete-pages'
    | '/tools/image-to-pdf'
    | '/tools/merge-pdf'
    | '/tools/pdf-to-image'
    | '/tools/rotate-pdf'
    | '/tools/split-pdf'
    | '/tools/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/tools/$slug'
    | '/tools/compress-pdf'
    | '/tools/delete-pages'
    | '/tools/image-to-pdf'
    | '/tools/merge-pdf'
    | '/tools/pdf-to-image'
    | '/tools/rotate-pdf'
    | '/tools/split-pdf'
    | '/tools'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/tools/$slug'
    | '/tools/compress-pdf'
    | '/tools/delete-pages'
    | '/tools/image-to-pdf'
    | '/tools/merge-pdf'
    | '/tools/pdf-to-image'
    | '/tools/rotate-pdf'
    | '/tools/split-pdf'
    | '/tools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  ToolsSlugRoute: typeof ToolsSlugRoute
  ToolsCompressPdfRoute: typeof ToolsCompressPdfRoute
  ToolsDeletePagesRoute: typeof ToolsDeletePagesRoute
  ToolsImageToPdfRoute: typeof ToolsImageToPdfRoute
  ToolsMergePdfRoute: typeof ToolsMergePdfRoute
  ToolsPdfToImageRoute: typeof ToolsPdfToImageRoute
  ToolsRotatePdfRoute: typeof ToolsRotatePdfRoute
  ToolsSplitPdfRoute: typeof ToolsSplitPdfRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/split-pdf': {
      id: '/tools/split-pdf'
      path: '/tools/split-pdf'
      fullPath: '/tools/split-pdf'
      preLoaderRoute: typeof ToolsSplitPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/rotate-pdf': {
      id: '/tools/rotate-pdf'
      path: '/tools/rotate-pdf'
      fullPath: '/tools/rotate-pdf'
      preLoaderRoute: typeof ToolsRotatePdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/pdf-to-image': {
      id: '/tools/pdf-to-image'
      path: '/tools/pdf-to-image'
      fullPath: '/tools/pdf-to-image'
      preLoaderRoute: typeof ToolsPdfToImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/merge-pdf': {
      id: '/tools/merge-pdf'
      path: '/tools/merge-pdf'
      fullPath: '/tools/merge-pdf'
      preLoaderRoute: typeof ToolsMergePdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/image-to-pdf': {
      id: '/tools/image-to-pdf'
      path: '/tools/image-to-pdf'
      fullPath: '/tools/image-to-pdf'
      preLoaderRoute: typeof ToolsImageToPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/delete-pages': {
      id: '/tools/delete-pages'
      path: '/tools/delete-pages'
      fullPath: '/tools/delete-pages'
      preLoaderRoute: typeof ToolsDeletePagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/compress-pdf': {
      id: '/tools/compress-pdf'
      path: '/tools/compress-pdf'
      fullPath: '/tools/compress-pdf'
      preLoaderRoute: typeof ToolsCompressPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$slug': {
      id: '/tools/$slug'
      path: '/tools/$slug'
      fullPath: '/tools/$slug'
      preLoaderRoute: typeof ToolsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  ToolsSlugRoute: ToolsSlugRoute,
  ToolsCompressPdfRoute: ToolsCompressPdfRoute,
  ToolsDeletePagesRoute: ToolsDeletePagesRoute,
  ToolsImageToPdfRoute: ToolsImageToPdfRoute,
  ToolsMergePdfRoute: ToolsMergePdfRoute,
  ToolsPdfToImageRoute: ToolsPdfToImageRoute,
  ToolsRotatePdfRoute: ToolsRotatePdfRoute,
  ToolsSplitPdfRoute: ToolsSplitPdfRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
