/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as ToolsMergePdfRouteImport } from './routes/tools.merge-pdf'
import { Route as ToolsImageToPdfRouteImport } from './routes/tools.image-to-pdf'
import { Route as ToolsSlugRouteImport } from './routes/tools.$slug'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsMergePdfRoute = ToolsMergePdfRouteImport.update({
  id: '/tools/merge-pdf',
  path: '/tools/merge-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsImageToPdfRoute = ToolsImageToPdfRouteImport.update({
  id: '/tools/image-to-pdf',
  path: '/tools/image-to-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSlugRoute = ToolsSlugRouteImport.update({
  id: '/tools/$slug',
  path: '/tools/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/tools/image-to-pdf': typeof ToolsImageToPdfRoute
  '/tools/merge-pdf': typeof ToolsMergePdfRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/tools/image-to-pdf': typeof ToolsImageToPdfRoute
  '/tools/merge-pdf': typeof ToolsMergePdfRoute
  '/tools': typeof ToolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/tools/image-to-pdf': typeof ToolsImageToPdfRoute
  '/tools/merge-pdf': typeof ToolsMergePdfRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/tools/$slug'
    | '/tools/image-to-pdf'
    | '/tools/merge-pdf'
    | '/tools/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/tools/$slug'
    | '/tools/image-to-pdf'
    | '/tools/merge-pdf'
    | '/tools'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/tools/$slug'
    | '/tools/image-to-pdf'
    | '/tools/merge-pdf'
    | '/tools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  ToolsSlugRoute: typeof ToolsSlugRoute
  ToolsImageToPdfRoute: typeof ToolsImageToPdfRoute
  ToolsMergePdfRoute: typeof ToolsMergePdfRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/merge-pdf': {
      id: '/tools/merge-pdf'
      path: '/tools/merge-pdf'
      fullPath: '/tools/merge-pdf'
      preLoaderRoute: typeof ToolsMergePdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/image-to-pdf': {
      id: '/tools/image-to-pdf'
      path: '/tools/image-to-pdf'
      fullPath: '/tools/image-to-pdf'
      preLoaderRoute: typeof ToolsImageToPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$slug': {
      id: '/tools/$slug'
      path: '/tools/$slug'
      fullPath: '/tools/$slug'
      preLoaderRoute: typeof ToolsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  ToolsSlugRoute: ToolsSlugRoute,
  ToolsImageToPdfRoute: ToolsImageToPdfRoute,
  ToolsMergePdfRoute: ToolsMergePdfRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
